networks:
  sber-test-task:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

services:
  sber-test-task_main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sber-test-task_main
    networks:
      - sber-test-task
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./app:/app/app

  migrations:
    build: .
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: ["uv", "run", "alembic", "upgrade", "head"]
    restart: "no"
    networks:
      - sber-test-task

  postgres:
    image: postgres:16
    container_name: postgres_sber_test_task
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-assigna-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-assigna-user123}
      POSTGRES_DB: ${POSTGRES_DB:-career-main}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sber-test-task
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5


  # redis:
  #   image: redis:latest
  #   container_name: redis_iyul
  #   restart: unless-stopped
  #   ports:
  #     - "${REDIS_PORT:-6379}:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - sber-test-task


volumes:
  postgres_data:
  redis_data: